name: ca_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: semigradsky <email@example.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  args: any
  rpc: any

#dev_dependencies:
#  test: ^0.12.30
